import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Download, Github, Linkedin, Menu, X, Cloud, Code2, Award, GraduationCap, MapPin, Mail, Server, ShieldCheck, Terminal, Check, Trophy, Cpu, Database, ChevronDown, ChevronUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import heroImage from '@/assets/aditi-narang-portrait.png.asset.json';
import resume from '@/assets/resume.asset.json';
import { profile, projects, skills, experiences, type Project } from '@/lib/portfolio-data';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Aditi Narang — Cloud & DevOps · AI/ML Portfolio' },
    { name: 'description', content: 'Meet Aditi Narang, a 3× AWS-certified CSE (AI & ML) student at KIET. Explore secure cloud architecture, Python automation, projects and leadership.' },
    { property: 'og:title', content: 'Aditi Narang — Cloud, DevOps & AI/ML' },
    { property: 'og:description', content: '3× AWS certified. 300+ problems solved. Real-world cloud infrastructure and software projects by Aditi Narang.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: Index,
});
const navigation = ['About', 'Projects', 'Skills', 'Experience', 'Achievements', 'Contact'];
const categories = ['All projects', 'Cloud & DevOps', 'Software', 'AI/ML'] as const;
function SectionTitle({ number, label, title, description }: { number: string; label: string; title: string; description?: string }) {
  return <div><div className="eyebrow">{number} / {label}</div><h2>{title}</h2>{description && <p className="section-intro">{description}</p>}</div>;
}
function SocialLinks() { return <div className="social-links"><a href={profile.github} target="_blank" rel="noreferrer"><Github size={15} />GitHub<ArrowUpRight size={12} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={15} />LinkedIn<ArrowUpRight size={12} /></a></div>; }
function ProjectVisual({ project, index }: { project: Project; index: number }) {
  return <div className="project-visual" aria-hidden="true"><span className="visual-index">PROJECT / 0{index + 1}</span>
    {project.visual === 'architecture' && <div className="architecture"><div className="architecture-node"><ShieldCheck size={25} /><span>VPC / IAM</span></div><ArrowRight /><div className="architecture-node"><Server size={25} /><span>FARGATE</span></div><ArrowRight /><div className="architecture-node"><Database size={25} /><span>PRIVATE</span></div></div>}
    {project.visual === 'terminal' && <div className="terminal"><div className="terminal-dots"><i/><i/><i/></div><div className="command">$ {project.title.includes('SSH') ? 'ssh -i key.pem ec2-user@server' : 'python automate_aws.py'}</div><div>Initializing secure connection...</div><div className="output">✓ {project.title.includes('SSH') ? 'Key-based authentication successful' : 'AWS resources configured'}</div><div className="command">$ _</div></div>}
    {project.visual === 'monitor' && <div className="monitor"><div className="monitor-header">{project.title.includes('Monitor') ? 'MONITORX / OVERVIEW' : 'INFRASTRUCTURE / HEALTH'}<span>● HEALTHY</span></div><div className="chart-bars">{Array.from({length: 24}, (_,i) => <i key={i}/>)}</div></div>}
    {project.visual === 'code' && <div className="terminal"><div className="terminal-dots"><i/><i/><i/></div><div className="command">{project.category === 'AI/ML' ? '// exploring with Claude' : '// built with the MERN stack'}</div><div>{project.category === 'AI/ML' ? 'const idea = await explore();' : 'const app = express();'}</div><div className="output">{project.category === 'AI/ML' ? 'learn → build → iterate' : 'app.use("/api", routes);'}</div><div className="command">{project.category === 'AI/ML' ? '60 days. One challenge.' : 'export default app;'}</div></div>}
  </div>;
}
function ProjectCard({ project, index }: { project: Project; index: number }) {
  const [expanded, setExpanded] = useState(false);
  return <article className="project-card"><ProjectVisual project={project} index={index}/><div className="project-body"><div className="project-label">{project.label}</div><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="tech-list">{project.tech.map(t => <span key={t}>{t}</span>)}</div><div className="project-footer"><Button asChild variant="ghost" size="sm" className="px-0"><a href={project.repo || `${profile.github}?tab=repositories`} target="_blank" rel="noreferrer"><Github size={13}/>{project.repo ? 'Source code' : 'GitHub profile'}<ArrowUpRight size={12}/></a></Button><Button variant="ghost" size="sm" onClick={() => setExpanded(!expanded)} aria-expanded={expanded} aria-label={`${expanded ? 'Hide' : 'Show'} ${project.title} details`}>Details{expanded ? <ChevronUp/> : <ChevronDown/>}</Button></div>{expanded && <div className="project-detail"><ul>{project.highlights.map(h => <li key={h}>{h}</li>)}</ul></div>}</div></article>;
}
function Index() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [active, setActive] = useState('');
  const [filter, setFilter] = useState<(typeof categories)[number]>('All projects');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { for (const entry of entries) if(entry.isIntersecting) setActive(entry.target.id); }, { rootMargin: '-15% 0px -60% 0px' });
    for (const item of navigation) { const section = document.getElementById(item.toLowerCase()); if(section) observer.observe(section); }
    return () => observer.disconnect();
  }, []);
  const filtered = projects.filter(p => filter === 'All projects' || p.category === filter);
  return <>
    <header className="site-header"><div className="container header-inner"><a href="#home" className="brand" aria-label="Aditi Narang home"><span className="brand-symbol">&lt;/&gt;</span>Aditi Narang<span className="text-primary">.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(n => <a key={n} className={active === n.toLowerCase() ? 'active' : ''} href={`#${n.toLowerCase()}`}>{n}</a>)}</nav><div className="header-actions"><Button asChild variant="outline" size="sm" className="header-resume"><a href={resume.url} download="Aditi-Narang-Resume.pdf" target="_blank" rel="noreferrer"><Download/>Résumé</a></Button><Button className="menu-trigger" variant="ghost" size="icon" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</Button></div></div>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(n => <a key={n} href={`#${n.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{n}</a>)}<a href={resume.url} target="_blank" rel="noreferrer">Download résumé <Download size={14}/></a></nav>}</header>
    <main>
      <section id="home" className="hero"><img className="hero-image" src={heroImage.url} alt="Professional portrait of Aditi Narang" width={1254} height={1254} fetchPriority="high"/><div className="container hero-content"><div className="availability"><span className="status-dot"/>Open to internships & placement opportunities</div><p className="intro">HELLO WORLD, I'M</p><h1>Aditi Narang</h1><p className="hero-role">CSE (AI & ML) Student <span className="text-muted-foreground">|</span> Cloud & DevOps <span className="text-muted-foreground">|</span> AI/ML</p><p className="hero-description">Building secure cloud infrastructure. Automating the everyday.<br className="hidden md:block"/> Turning ideas into real-world solutions with AWS, code, and a curious mind.</p><div className="hero-cta"><Button asChild><a href="#projects">View projects<ArrowUpRight/></a></Button><Button asChild variant="outline"><a href={resume.url} target="_blank" rel="noreferrer" download="Aditi-Narang-Resume.pdf"><Download/>Download résumé</a></Button></div><SocialLinks/><div className="hero-caption"><span className="status-dot"/> BUILT FOR THE CLOUD. GROUNDED IN CODE.</div></div></section>
      <div className="metrics"><div className="container metrics-inner">{[{icon:Award, value:'3× AWS',label:'Certified'}, {icon:Code2,value:'300+',label:'Coding problems solved'}, {icon:GraduationCap,value:profile.cgpa,label:'CGPA · KIET University'}, {icon:Trophy,value:'2× NPTEL',label:'Topper · Silver badges'}].map(({icon:Icon,value,label}) => <div className="metric" key={label}><Icon/><div><strong>{value}</strong><span>{label}</span></div></div>)}</div></div>
      <section className="section" id="projects"><div className="container"><div className="section-heading"><SectionTitle number="01" label="Selected work" title="Ideas, engineered into reality." description="Hands-on projects across cloud infrastructure, automation, and software."/><a className="section-link" href={`${profile.github}?tab=repositories`} target="_blank" rel="noreferrer">All repositories<Github size={15}/><ArrowUpRight size={14}/></a></div><div className="filter-tabs" aria-label="Filter projects">{categories.map(c => <Button key={c} variant={c === filter ? 'secondary' : 'ghost'} size="sm" onClick={() => setFilter(c)} aria-pressed={c === filter}>{c}{c === 'All projects' && <span className="text-muted-foreground">07</span>}</Button>)}</div><div className="project-grid">{filtered.map(p => <ProjectCard key={p.title} project={p} index={projects.indexOf(p)}/>)}</div></div></section>
      <section className="section" id="about"><div className="container about-grid"><div><SectionTitle number="02" label="A little about me" title="Curiosity is my starting point."/><div className="about-copy"><p>I'm a third-year <strong>Computer Science & Engineering (AI & ML)</strong> student at KIET Deemed to be University, with a focus on <strong>Cloud, DevOps, and intelligent software.</strong></p><p>I enjoy understanding how systems work — and making them work better. From secure AWS networking to Python automation, my learning is rooted in building, testing, and solving real problems.</p><p>Beyond code, I lead student communities, coordinate events, and bring the same ownership to a team that I bring to a project.</p></div><div className="about-facts"><span><MapPin size={14}/>India</span><span><Code2 size={14}/>Java & Python</span><span><Cloud size={14}/>Cloud-first mindset</span></div></div><div id="education" className="education self-center"><div className="eyebrow">Education</div><GraduationCap className="text-primary" size={29}/><h3>B.Tech in Computer Science<br/>& Engineering (AI & ML)</h3><p>KIET Deemed to be University</p><div className="education-meta"><span>2024 — 2028 · 3rd year</span><strong>{profile.cgpa} CGPA</strong></div><p className="mt-6">Holy Angel’s Convent School<br/>Class XII: 91.8% · Top 5<br/>Class X: 96.2% · Top 3</p></div></div></section>
      <section className="section" id="skills"><div className="container"><SectionTitle number="03" label="Technical toolkit" title="The tools behind the work." description="A practical foundation, built through projects and continuous learning."/><div className="skills-grid">{skills.map((s,i) => {const Icon=[Cloud,Terminal,Database,Cpu][i]; return <div className="skill-group" key={s.category}><h3>{Icon && <Icon/>}{s.category}</h3><div className="skill-badges">{s.items.map(t => <span key={t} title={t}>{t}</span>)}</div></div>;})}</div></div></section>
      <section className="section" id="experience"><div className="container"><SectionTitle number="04" label="Experience & leadership" title="Learning by doing. Leading by example." description="From hands-on cloud work to building stronger student communities."/><div className="timeline">{experiences.map(e => <article className="timeline-row" key={e.role}><div className="timeline-date">{e.period}</div><div className="timeline-main"><h3>{e.role}</h3><h4>{e.organization}</h4><p>{e.detail}</p></div><span className="timeline-tag">{e.tag}</span></article>)}</div></div></section>
      <section className="section" id="achievements"><div className="container"><SectionTitle number="05" label="Certifications & achievements" title="Credentials backed by curiosity." description="Milestones in a continuous journey of learning and building."/><div className="cert-grid">{['Solutions Architect', 'Cloud Practitioner', 'CloudOps Associate'].map(c => <article className="cert-card" key={c}><div className="cert-logo"><span className="aws-word">aws</span></div><div className="project-label">AWS CERTIFIED</div><h3>{c}</h3><p>Amazon Web Services</p><div className="cert-status"><ShieldCheck size={13}/>CERTIFIED</div></article>)}</div><div className="achievement-strip"><div><Trophy size={23}/><span>2× NPTEL Topper<br/><strong className="text-foreground font-medium">Silver badges · Top 1% ranks</strong></span></div><div><Cpu size={23}/><span>AWS AI & ML Scholars<br/><strong className="text-foreground font-medium">2026 Challenge</strong></span></div><div><Award size={23}/><span>LeetCode<br/><strong className="text-foreground font-medium">50 Days Badge · 2026</strong></span></div></div></div></section>
      <section className="section" id="coding"><div className="container coding-grid"><div><SectionTitle number="06" label="Problem solving" title="One problem. A better approach."/><p className="section-intro">Consistent practice in data structures, algorithms, and the craft of writing better code.</p><div className="coding-stats"><div><strong>300<span className="text-primary text-3xl">+</span></strong><span>Problems across platforms</span></div><div><strong>125<span className="text-primary text-3xl">+</span></strong><span>LeetCode problems</span></div></div><div className="tech-list"><span>Data Structures & Algorithms</span><span>Java</span><span>Python</span><span>Problem solving</span></div></div><div className="coding-panel"><div className="coding-panel-header"><span><Code2 size={15} className="inline mr-2"/>THE MINDSET</span><span>practice.py</span></div><pre className="code-snippet"><span>while</span> learning:<br/>{'    '}understand(problem)<br/>{'    '}build(solution)<br/>{'    '}test(edge_cases)<br/>{'    '}<span>iterate</span>()</pre><div className="coding-panel-footer"><Check size={13}/>Consistency over shortcuts.</div></div></div></section>
      <section className="contact-section" id="contact"><div className="container contact-inner"><div><div className="eyebrow">07 / Let's connect</div><h2>Let's build what’s next<span className="text-primary">.</span></h2><p>Looking for a curious engineer who takes ownership? I'm open to Software Engineering, Cloud/DevOps, and AI/ML opportunities.</p><div className="availability mt-4"><span className="status-dot"/>Available for internships & placements</div></div><div className="contact-actions"><Button asChild size="lg"><a href={`mailto:${profile.email}`}><Mail/>{profile.email}<ArrowUpRight/></a></Button><SocialLinks/><Button asChild variant="ghost" className="px-0"><a href={resume.url} download="Aditi-Narang-Resume.pdf" target="_blank" rel="noreferrer"><Download/>Download résumé</a></Button></div></div></section>
    </main><footer className="footer"><div className="container footer-inner"><a href="#home" className="brand"><span className="brand-symbol">&lt;/&gt;</span>Aditi Narang<span className="text-primary">.</span></a><span>© 2026 Aditi Narang · Built with intention.</span><a className="section-link" href="#home">Back to top<ArrowDown size={13} className="rotate-180"/></a></div></footer>
  </>;
}
